on:
  push:
    brance: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: "before listing files"
        run: ls

      - uses: actions/checkout@v3

      - name: "After listing files"
        run: ls -a
